import type { Property } from "@/lib/properties";

const saguapacSurImages = Array.from(
  { length: 10 },
  (_, index) => `/images/properties/saguapac-sur-directo/${String(index + 1).padStart(2, "0")}.webp`,
);

export const curatedRentalProperties: Property[] = [
  {
    id: "curated-direct-1406283610966290",
    slug: "casa-3-dormitorios-saguapac-sur-3500",
    title: "Casa de 3 dormitorios en Saguapac Sur",
    type: "Casa",
    operation: "Alquiler",
    price: 3500,
    currency: "BOB",
    city: "Santa Cruz de la Sierra",
    zone: "Saguapac Sur",
    address: "Barrio Saguapac Sur, entre 5to y 6to anillo, Av. Santos Dumont",
    bedrooms: 3,
    bathrooms: 2,
    garage: 0,
    area: 0,
    pets: false,
    furnished: false,
    security: false,
    pool: false,
    patio: true,
    grill: false,
    elevator: false,
    shortDescription: "Casa independiente con tres dormitorios, patio y garaje opcional.",
    longDescription: [
      "Casa en alquiler en el barrio Saguapac Sur, entre 5to y 6to anillo de la Av. Santos Dumont.",
      "",
      "Cuenta con:",
      "- 3 dormitorios",
      "- 2 baños",
      "- Sala y comedor",
      "- Cocina",
      "- Lavandería",
      "- Patio",
      "- Gas domiciliario",
      "- Aire acondicionado",
      "",
      "Precio sin garaje: Bs 3.500 mensuales.",
      "Precio con garaje: Bs 4.500 mensuales.",
      "",
      "Calle asfaltada y tranquila, cerca del Colegio Caritas y de las líneas 108 y 78.",
      "Trato directo con la propietaria, sin intermediarios ni inmobiliaria.",
    ].join("\n"),
    requirements: [
      "Garantía: consultar con la propietaria",
      "Garaje opcional por Bs 1.000 adicionales",
      "Sin comisión de intermediación",
    ],
    images: saguapacSurImages,
    mapUrl: "https://maps.app.goo.gl/1YCspShPt7k3hQqt7?g_st=ic",
    whatsapp: "59163612202",
    idealFor: ["Familias", "Zonas tranquilas"],
    tags: ["3 dormitorios", "Patio", "Gas domiciliario", "Garaje opcional"],
    listingPlan: "standard",
    publisher: {
      name: "Propietaria directa",
      shortName: "PD",
      kind: "owner",
      verified: false,
      brandColor: "#087c65",
      brandTextColor: "#ffffff",
    },
    agent: {
      name: "Propietaria Saguapac Sur",
      role: "Propietaria directa",
      email: "",
      phone: "+591 63612202",
      whatsapp: "59163612202",
      photo: "",
      areas: ["Saguapac Sur"],
      verified: false,
      responseTime: "Contacto directo por WhatsApp.",
    },
    featured: false,
    published: true,
    availabilityConfirmedAt: "2026-10-01T12:00:00.000-04:00",
    isSeeded: false,
    coordinates: { lat: -17.83798, lng: -63.18797 },
    neighborhoodHighlights: ["Av. Santos Dumont", "Colegio Caritas", "Líneas 108 y 78"],
    rentalDetails: {
      title: "Casa de 3 dormitorios en Saguapac Sur",
      type: "Casa",
      zone: "Saguapac Sur",
      address: "Barrio Saguapac Sur, entre 5to y 6to anillo, Av. Santos Dumont",
      bedrooms: 3,
      bathrooms: 2,
      garage: 0,
      area: null,
      pets: false,
      petsPolicy: "consult",
      furnished: false,
      security: false,
      pool: false,
      patio: true,
      grill: false,
      elevator: false,
      price: 3500,
      currency: "BOB",
      exchangeRate: null,
      commonExpenses: 0,
      guarantee: "Consultar con el propietario",
      guaranteeAmount: null,
      parkingNote: "Garaje opcional por Bs 1.000 adicionales",
      description: "Casa independiente de tres dormitorios con patio, gas domiciliario y aire acondicionado. Garaje opcional.",
    },
  },
];

export function getCuratedRentalBySlug(slug: string) {
  return curatedRentalProperties.find((property) => property.slug === slug);
}
