import type { Property } from "@/lib/properties";

const saguapacSurImages = Array.from(
  { length: 10 },
  (_, index) => `/images/properties/saguapac-sur-directo/${String(index + 1).padStart(2, "0")}.webp`,
);

const radial26Images = Array.from(
  { length: 12 },
  (_, index) => `/images/properties/radial-26-directo/${String(index + 1).padStart(2, "0")}.webp`,
);

const guapiloImages = Array.from(
  { length: 8 },
  (_, index) => `/images/properties/monoambiente-guapilo-directo/${String(index + 1).padStart(2, "0")}.webp`,
);

const barrio18MarzoImages = Array.from(
  { length: 8 },
  (_, index) => `/images/properties/barrio-18-marzo-directo/${String(index + 1).padStart(2, "0")}.webp`,
);

export const curatedRentalProperties: Property[] = [
  {
    id: "curated-direct-1406283610966290",
    slug: "casa-3-dormitorios-saguapac-sur-3500",
    title: "Casa de 3 dormitorios en Saguapac Sur",
    type: "Casa",
    operation: "Alquiler",
    price: 3500,
    currency: "BOB",
    city: "Santa Cruz de la Sierra",
    zone: "Saguapac Sur",
    address: "Barrio Saguapac Sur, entre 5to y 6to anillo, Av. Santos Dumont",
    bedrooms: 3,
    bathrooms: 2,
    garage: 0,
    area: 0,
    pets: false,
    furnished: false,
    security: false,
    pool: false,
    patio: true,
    grill: false,
    elevator: false,
    shortDescription: "Casa independiente con tres dormitorios, patio y garaje opcional.",
    longDescription: [
      "Casa en alquiler en el barrio Saguapac Sur, entre 5to y 6to anillo de la Av. Santos Dumont.",
      "",
      "Cuenta con:",
      "- 3 dormitorios",
      "- 2 baños",
      "- Sala y comedor",
      "- Cocina",
      "- Lavandería",
      "- Patio",
      "- Gas domiciliario",
      "- Aire acondicionado",
      "",
      "Precio sin garaje: Bs 3.500 mensuales.",
      "Precio con garaje: Bs 4.500 mensuales.",
      "",
      "Calle asfaltada y tranquila, cerca del Colegio Caritas y de las líneas 108 y 78.",
      "Trato directo con la propietaria, sin intermediarios ni inmobiliaria.",
    ].join("\n"),
    requirements: [
      "Garantía: consultar con la propietaria",
      "Garaje opcional por Bs 1.000 adicionales",
      "Sin comisión de intermediación",
    ],
    images: saguapacSurImages,
    mapUrl: "https://maps.app.goo.gl/1YCspShPt7k3hQqt7?g_st=ic",
    whatsapp: "59163612202",
    idealFor: ["Familias", "Zonas tranquilas"],
    tags: ["3 dormitorios", "Patio", "Gas domiciliario", "Garaje opcional"],
    listingPlan: "standard",
    publisher: {
      name: "Propietaria directa",
      shortName: "PD",
      kind: "owner",
      verified: false,
      brandColor: "#087c65",
      brandTextColor: "#ffffff",
    },
    agent: {
      name: "Propietaria Saguapac Sur",
      role: "Propietaria directa",
      email: "",
      phone: "+591 63612202",
      whatsapp: "59163612202",
      photo: "",
      areas: ["Saguapac Sur"],
      verified: false,
      responseTime: "Contacto directo por WhatsApp.",
    },
    featured: false,
    published: true,
    availabilityConfirmedAt: "2026-10-01T12:00:00.000-04:00",
    isSeeded: false,
    coordinates: { lat: -17.83798, lng: -63.18797 },
    neighborhoodHighlights: ["Av. Santos Dumont", "Colegio Caritas", "Líneas 108 y 78"],
    rentalDetails: {
      title: "Casa de 3 dormitorios en Saguapac Sur",
      type: "Casa",
      zone: "Saguapac Sur",
      address: "Barrio Saguapac Sur, entre 5to y 6to anillo, Av. Santos Dumont",
      bedrooms: 3,
      bathrooms: 2,
      garage: 0,
      area: null,
      pets: false,
      petsPolicy: "consult",
      furnished: false,
      security: false,
      pool: false,
      patio: true,
      grill: false,
      elevator: false,
      price: 3500,
      currency: "BOB",
      exchangeRate: null,
      commonExpenses: 0,
      guarantee: "Consultar con el propietario",
      guaranteeAmount: null,
      parkingNote: "Garaje opcional por Bs 1.000 adicionales",
      description: "Casa independiente de tres dormitorios con patio, gas domiciliario y aire acondicionado. Garaje opcional.",
    },
  },
  {
    id: "curated-direct-1443637447679441",
    slug: "departamento-1-dormitorio-radial-26-4000",
    title: "Departamento de 1 dormitorio cerca de Radial 26",
    type: "Departamento",
    operation: "Alquiler",
    price: 4000,
    currency: "BOB",
    city: "Santa Cruz de la Sierra",
    zone: "Zona Norte",
    address: "4to anillo y Radial 26, entre Las Brisas y Ventura Mall",
    bedrooms: 1,
    bathrooms: 2,
    garage: 1,
    area: 56,
    pets: false,
    furnished: false,
    security: false,
    pool: true,
    patio: false,
    grill: true,
    elevator: false,
    shortDescription: "Departamento con balcón, parqueo techado y expensas incluidas.",
    longDescription: [
      "Departamento en alquiler directo con el propietario, cerca del 4to anillo y la Radial 26.",
      "",
      "Cuenta con:",
      "- 1 dormitorio amplio con aire acondicionado, vestidor y balcón",
      "- Sala comedor con aire acondicionado y balcón",
      "- Cocina amoblada",
      "- 2 baños completos",
      "- Parqueo techado",
      "- 56 m²",
      "",
      "Áreas comunes:",
      "- Piscina",
      "- Gimnasio",
      "- Cine",
      "- Cowork",
      "- Sala social",
      "- Parque infantil",
      "- Churrasqueras",
      "",
      "El alquiler incluye expensas.",
      "Trato directo con el dueño, sin comisión inmobiliaria.",
      "Contacto alternativo: 76313555.",
    ].join("\n"),
    requirements: [
      "1 mes de alquiler adelantado",
      "1 mes de garantía",
      "Expensas incluidas",
      "Sin comisión de intermediación",
    ],
    images: radial26Images,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=-17.7481004,-63.1855663",
    whatsapp: "59176355305",
    idealFor: ["Personas solas", "Parejas", "Home office"],
    tags: ["1 dormitorio", "Balcón", "Parqueo", "Piscina", "Expensas incluidas"],
    listingPlan: "standard",
    publisher: {
      name: "Javier Terrazas Brañez",
      shortName: "JT",
      kind: "owner",
      verified: false,
      brandColor: "#087c65",
      brandTextColor: "#ffffff",
    },
    agent: {
      name: "Javier Terrazas Brañez",
      role: "Propietario directo",
      email: "",
      phone: "+591 76355305",
      whatsapp: "59176355305",
      photo: "",
      areas: ["Zona Norte"],
      verified: false,
      responseTime: "Contacto directo por WhatsApp.",
    },
    featured: false,
    published: true,
    availabilityConfirmedAt: "2026-10-01T14:00:00.000-04:00",
    isSeeded: false,
    coordinates: { lat: -17.7481004, lng: -63.1855663 },
    neighborhoodHighlights: ["Las Brisas", "Ventura Mall", "Radial 26"],
    rentalDetails: {
      title: "Departamento de 1 dormitorio cerca de Radial 26",
      type: "Departamento",
      zone: "Zona Norte",
      address: "4to anillo y Radial 26, entre Las Brisas y Ventura Mall",
      bedrooms: 1,
      bathrooms: 2,
      garage: 1,
      area: 56,
      pets: false,
      petsPolicy: "consult",
      furnished: false,
      security: false,
      pool: true,
      patio: false,
      grill: true,
      elevator: false,
      price: 4000,
      currency: "BOB",
      exchangeRate: null,
      commonExpenses: 0,
      guarantee: "1 mes de alquiler",
      guaranteeAmount: null,
      parkingNote: "1 parqueo techado incluido",
      description: "Departamento de un dormitorio con dos baños, balcones, parqueo y áreas sociales. Expensas incluidas.",
    },
  },
  {
    id: "curated-direct-1126033656771635",
    slug: "monoambiente-semiindependiente-canal-guapilo-1200",
    title: "Monoambiente semiindependiente cerca de Canal Guapilo",
    type: "Departamento",
    operation: "Alquiler",
    price: 1200,
    currency: "BOB",
    city: "Santa Cruz de la Sierra",
    zone: "Villa 1ro de Mayo",
    address: "A 2 cuadras de Av. Jenecheru y a 1 cuadra de Av. Canal Guapilo",
    bedrooms: 1,
    bathrooms: 1,
    garage: 0,
    area: 0,
    pets: false,
    furnished: false,
    security: false,
    pool: false,
    patio: false,
    grill: false,
    elevator: false,
    shortDescription: "Monoambiente semiindependiente en planta alta, sin garantía.",
    longDescription: [
      "Monoambiente semiindependiente en alquiler cerca de las avenidas Jenecheru y Canal Guapilo.",
      "",
      "Cuenta con:",
      "- 1 dormitorio",
      "- 1 baño independiente",
      "- Cocina comedor con lavaplatos",
      "- Instalación para lavadora",
      "- Planta alta, primer piso",
      "",
      "En el inmueble viven otros inquilinos, pero el monoambiente tiene sus propios ambientes.",
      "Los servicios de luz y agua se pagan por separado.",
      "No se solicita garantía.",
      "Trato directo con el dueño.",
    ].join("\n"),
    requirements: [
      "1 mes de alquiler adelantado",
      "Sin garantía",
      "Luz y agua por separado",
      "Sin comisión de intermediación",
    ],
    images: guapiloImages,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=-17.7830,-63.1217",
    whatsapp: "59163422199",
    idealFor: ["Personas solas", "Parejas"],
    tags: ["Monoambiente", "Sin garantía", "Cocina independiente", "Lavandería"],
    listingPlan: "standard",
    publisher: {
      name: "Roberto Avila",
      shortName: "RA",
      kind: "owner",
      verified: false,
      brandColor: "#087c65",
      brandTextColor: "#ffffff",
    },
    agent: {
      name: "Roberto Avila",
      role: "Propietario directo",
      email: "",
      phone: "+591 63422199",
      whatsapp: "59163422199",
      photo: "",
      areas: ["Villa 1ro de Mayo"],
      verified: false,
      responseTime: "Contacto directo por WhatsApp.",
    },
    featured: false,
    published: true,
    availabilityConfirmedAt: "2026-10-01T14:00:00.000-04:00",
    isSeeded: false,
    coordinates: { lat: -17.783, lng: -63.1217 },
    neighborhoodHighlights: ["Av. Jenecheru", "Av. Canal Guapilo", "Villa 1ro de Mayo"],
    rentalDetails: {
      title: "Monoambiente semiindependiente cerca de Canal Guapilo",
      type: "Monoambiente",
      zone: "Villa 1ro de Mayo",
      address: "A 2 cuadras de Av. Jenecheru y a 1 cuadra de Av. Canal Guapilo",
      bedrooms: 1,
      bathrooms: 1,
      garage: 0,
      area: null,
      pets: false,
      petsPolicy: "consult",
      furnished: false,
      security: false,
      pool: false,
      patio: false,
      grill: false,
      elevator: false,
      price: 1200,
      currency: "BOB",
      exchangeRate: null,
      commonExpenses: 0,
      guarantee: "Sin garantía",
      guaranteeAmount: null,
      parkingNote: "Consultar con el propietario",
      description: "Monoambiente semiindependiente en planta alta con dormitorio, baño, cocina comedor e instalación para lavadora.",
    },
  },
  {
    id: "curated-direct-2858018341238977",
    slug: "departamento-1-dormitorio-barrio-18-marzo-1650",
    title: "Departamento de 1 dormitorio en Barrio 18 de Marzo",
    type: "Departamento",
    operation: "Alquiler",
    price: 1650,
    currency: "BOB",
    city: "Santa Cruz de la Sierra",
    zone: "Barrio 18 de Marzo",
    address: "Barrio 18 de Marzo, Santa Cruz de la Sierra",
    bedrooms: 1,
    bathrooms: 1,
    garage: 0,
    area: 0,
    pets: false,
    furnished: false,
    security: false,
    pool: false,
    patio: false,
    grill: false,
    elevator: false,
    shortDescription: "Departamento con dormitorio amplio, sala y cocina comedor.",
    longDescription: [
      "Departamento en alquiler en el barrio 18 de Marzo.",
      "",
      "Cuenta con:",
      "- 1 dormitorio amplio con baño privado",
      "- Sala amplia",
      "- Cocina comedor",
      "",
      "Los servicios no están incluidos en el alquiler.",
      "La garantía es de Bs 1.000.",
      "Entrega inmediata y trato directo con el dueño.",
    ].join("\n"),
    requirements: [
      "1 mes de alquiler adelantado",
      "Garantía de Bs 1.000",
      "Servicios por separado",
      "Sin comisión de intermediación",
    ],
    images: barrio18MarzoImages,
    mapUrl: "https://www.google.com/maps/search/?api=1&query=-17.7905265,-63.1109101",
    whatsapp: "59172121100",
    idealFor: ["Personas solas", "Parejas"],
    tags: ["1 dormitorio", "Baño privado", "Cocina comedor", "Entrega inmediata"],
    listingPlan: "standard",
    publisher: {
      name: "Nayii Abdala",
      shortName: "NA",
      kind: "owner",
      verified: false,
      brandColor: "#087c65",
      brandTextColor: "#ffffff",
    },
    agent: {
      name: "Nayii Abdala",
      role: "Propietaria directa",
      email: "",
      phone: "+591 72121100",
      whatsapp: "59172121100",
      photo: "",
      areas: ["Barrio 18 de Marzo"],
      verified: false,
      responseTime: "Contacto directo por WhatsApp.",
    },
    featured: false,
    published: true,
    availabilityConfirmedAt: "2026-10-01T14:00:00.000-04:00",
    isSeeded: false,
    coordinates: { lat: -17.7905265, lng: -63.1109101 },
    neighborhoodHighlights: ["Barrio 18 de Marzo", "Villa 1ro de Mayo", "Av. Cumavi"],
    rentalDetails: {
      title: "Departamento de 1 dormitorio en Barrio 18 de Marzo",
      type: "Departamento",
      zone: "Barrio 18 de Marzo",
      address: "Barrio 18 de Marzo, Santa Cruz de la Sierra",
      bedrooms: 1,
      bathrooms: 1,
      garage: 0,
      area: null,
      pets: false,
      petsPolicy: "consult",
      furnished: false,
      security: false,
      pool: false,
      patio: false,
      grill: false,
      elevator: false,
      price: 1650,
      currency: "BOB",
      exchangeRate: null,
      commonExpenses: 0,
      guarantee: "Otro monto",
      guaranteeAmount: 1000,
      parkingNote: "Consultar con la propietaria",
      description: "Departamento con dormitorio amplio y baño privado, sala y cocina comedor. Servicios por separado.",
    },
  },
];

export function getCuratedRentalBySlug(slug: string) {
  return curatedRentalProperties.find((property) => property.slug === slug);
}
