import type { Property, PropertyAgent, PropertyPublisher } from "@/lib/properties";

const demoPublisher: PropertyPublisher = {
  name: "Propietario de prueba",
  shortName: "PD",
  kind: "owner",
  verified: false,
  brandColor: "#176b4d",
  brandTextColor: "#ffffff",
};

const apartmentPhotos = [
  "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1400&q=78",
  "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&w=1400&q=78",
  "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?auto=format&fit=crop&w=1400&q=78",
  "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1400&q=78",
  "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1400&q=78",
  "https://images.unsplash.com/photo-1554995207-c18c203602cb?auto=format&fit=crop&w=1400&q=78",
  "https://images.unsplash.com/photo-1600047509358-9dc75507daeb?auto=format&fit=crop&w=1400&q=78",
];

const housePhotos = [
  "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1400&q=78",
  "https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&w=1400&q=78",
  "https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1400&q=78",
  "https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1400&q=78",
  "https://images.unsplash.com/photo-1600566752355-35792bedcfea?auto=format&fit=crop&w=1400&q=78",
  "https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=1400&q=78",
  "https://images.unsplash.com/photo-1600607687644-c7171b42498f?auto=format&fit=crop&w=1400&q=78",
];

const availabilityConfirmedAt = "2026-07-27T12:00:00.000Z";

export const directRentalDemoProperties: Property[] = [
  makeDemo({
    id: "demo-direct-001",
    slug: "demo-monoambiente-equipetrol-norte",
    title: "Monoambiente amoblado en Equipetrol Norte",
    type: "Departamento",
    price: 2800,
    zone: "Equipetrol",
    address: "Equipetrol Norte, cerca de Av. San Martin",
    bedrooms: 1,
    bathrooms: 1,
    garage: 0,
    area: 42,
    pets: false,
    furnished: true,
    security: true,
    pool: false,
    patio: false,
    grill: false,
    elevator: true,
    shortDescription: "Monoambiente equipado, luminoso y listo para una persona.",
    longDescription: "Ambiente integrado con cocina equipada, ropero empotrado, aire acondicionado y baño privado. El edificio cuenta con ascensor, control de acceso y lavanderia compartida.",
    requirements: ["1 mes adelantado", "1 mes de garantia", "Sin comision inmobiliaria", "Contrato minimo de 6 meses"],
    idealFor: ["Persona sola", "Estudiantes", "Home office"],
    tags: ["Monoambiente", "Amoblado", "Ascensor", "Control de acceso"],
    coordinates: { lat: -17.7587, lng: -63.1968 },
    neighborhoodHighlights: ["Av. San Martin", "Cafes", "Transporte"],
    images: rotatePhotos(apartmentPhotos, 0),
    ownerIndex: 1,
  }),
  makeDemo({
    id: "demo-direct-002",
    slug: "demo-departamento-dos-dormitorios-urbari",
    title: "Departamento de 2 dormitorios en Urbari",
    type: "Departamento",
    price: 3500,
    zone: "Urbari",
    address: "Barrio Urbari, entre 2do y 3er anillo",
    bedrooms: 2,
    bathrooms: 2,
    garage: 1,
    area: 85,
    pets: true,
    furnished: false,
    security: true,
    pool: false,
    patio: false,
    grill: true,
    elevator: true,
    shortDescription: "Departamento funcional con parqueo y balcon, acepta mascotas pequeñas.",
    longDescription: "Cuenta con living comedor, cocina con cajoneria, dormitorio principal en suite, segundo dormitorio, baño compartido y balcon. Incluye parqueo y churrasquera comun.",
    requirements: ["1 mes adelantado", "1 mes de garantia", "Sin comision inmobiliaria", "Mascota sujeta a acuerdo"],
    idealFor: ["Parejas", "Familias", "Mascotas"],
    tags: ["Balcon", "Parqueo", "Mascotas", "Churrasquera"],
    coordinates: { lat: -17.7978, lng: -63.1908 },
    neighborhoodHighlights: ["2do anillo", "Supermercados", "Colegios"],
    images: rotatePhotos(apartmentPhotos, 1),
    ownerIndex: 2,
  }),
  makeDemo({
    id: "demo-direct-003",
    slug: "demo-casa-familiar-hamacas",
    title: "Casa familiar con patio en Hamacas",
    type: "Casa",
    price: 5200,
    zone: "Hamacas",
    address: "Zona Hamacas, calle residencial pavimentada",
    bedrooms: 3,
    bathrooms: 2,
    garage: 2,
    area: 180,
    pets: true,
    furnished: false,
    security: true,
    pool: false,
    patio: true,
    grill: true,
    elevator: false,
    shortDescription: "Casa independiente con patio, churrasquera y garaje para dos vehiculos.",
    longDescription: "La casa tiene tres dormitorios, living comedor, cocina cerrada, dos baños, lavanderia, patio trasero y churrasquera. Cuenta con porton electrico y cerca electrica.",
    requirements: ["1 mes adelantado", "1 mes de garantia", "Sin comision inmobiliaria", "Servicios segun consumo"],
    idealFor: ["Familias", "Mascotas", "Zonas tranquilas"],
    tags: ["Patio", "Churrasquera", "Porton electrico", "Cerca electrica"],
    coordinates: { lat: -17.7086, lng: -63.1699 },
    neighborhoodHighlights: ["Zona norte", "Colegios", "Calles pavimentadas"],
    images: rotatePhotos(housePhotos, 0),
    ownerIndex: 3,
  }),
  makeDemo({
    id: "demo-direct-004",
    slug: "demo-monoambiente-centro-calle-velasco",
    title: "Monoambiente practico en el Centro",
    type: "Departamento",
    price: 2100,
    zone: "Centro",
    address: "Calle Velasco, zona Centro",
    bedrooms: 1,
    bathrooms: 1,
    garage: 0,
    area: 32,
    pets: false,
    furnished: true,
    security: true,
    pool: false,
    patio: false,
    grill: true,
    elevator: true,
    shortDescription: "Monoambiente compacto con expensas incluidas y acceso controlado.",
    longDescription: "Espacio amoblado con cama, ropero, cocina, baño privado y aire acondicionado. El edificio tiene ascensor, camaras y terraza con churrasquera.",
    requirements: ["1 mes adelantado", "1 mes de garantia", "Expensas incluidas", "Sin comision inmobiliaria"],
    idealFor: ["Persona sola", "Estudiantes", "Economicos"],
    tags: ["Monoambiente", "Expensas incluidas", "Amoblado", "Centro"],
    coordinates: { lat: -17.7831, lng: -63.1782 },
    neighborhoodHighlights: ["Universidades", "Transporte", "Comercio"],
    images: rotatePhotos(apartmentPhotos, 2),
    ownerIndex: 4,
  }),
  makeDemo({
    id: "demo-direct-005",
    slug: "demo-departamento-tres-dormitorios-av-beni",
    title: "Departamento amplio sobre Av. Beni",
    type: "Departamento",
    price: 4200,
    zone: "Av. Beni",
    address: "Av. Beni entre 4to y 5to anillo",
    bedrooms: 3,
    bathrooms: 2,
    garage: 1,
    area: 112,
    pets: true,
    furnished: false,
    security: true,
    pool: false,
    patio: false,
    grill: false,
    elevator: true,
    shortDescription: "Departamento de tres dormitorios con buena conexion y parqueo.",
    longDescription: "Distribucion familiar con sala comedor, cocina independiente, dormitorio principal en suite, dos dormitorios secundarios, baño compartido, lavanderia y parqueo cubierto.",
    requirements: ["1 mes adelantado", "1 mes de garantia", "Sin comision inmobiliaria", "Contrato minimo de 12 meses"],
    idealFor: ["Familias", "Mascotas", "Home office"],
    tags: ["3 dormitorios", "Parqueo", "Ascensor", "Lavanderia"],
    coordinates: { lat: -17.7318, lng: -63.1784 },
    neighborhoodHighlights: ["Av. Beni", "Transporte", "Supermercados"],
    images: rotatePhotos(apartmentPhotos, 3),
    ownerIndex: 5,
  }),
  makeDemo({
    id: "demo-direct-006",
    slug: "demo-casa-piscina-zona-norte",
    title: "Casa de 4 dormitorios con piscina en zona norte",
    type: "Casa",
    price: 6500,
    zone: "Zona Norte",
    address: "Zona norte, entre 7mo y 8vo anillo",
    bedrooms: 4,
    bathrooms: 3,
    garage: 2,
    area: 260,
    pets: true,
    furnished: false,
    security: true,
    pool: true,
    patio: true,
    grill: true,
    elevator: false,
    shortDescription: "Casa familiar con piscina, patio amplio y seguridad.",
    longDescription: "Cuenta con cuatro dormitorios, uno en suite, escritorio, cocina cerrada, living comedor, dependencia de servicio, patio con piscina y galeria con churrasquera.",
    requirements: ["1 mes adelantado", "2 meses de garantia", "Sin comision inmobiliaria", "Contrato minimo de 12 meses"],
    idealFor: ["Familias", "Mascotas", "Home office"],
    tags: ["Piscina", "Patio", "Escritorio", "Seguridad"],
    coordinates: { lat: -17.6908, lng: -63.1765 },
    neighborhoodHighlights: ["Zona norte", "Condominios", "Colegios"],
    images: rotatePhotos(housePhotos, 1),
    ownerIndex: 1,
  }),
  makeDemo({
    id: "demo-direct-007",
    slug: "demo-departamento-amoblado-equipetrol",
    title: "Departamento amoblado con amenities en Equipetrol",
    type: "Departamento",
    price: 4800,
    zone: "Equipetrol",
    address: "Equipetrol, cerca del Ventura Mall",
    bedrooms: 2,
    bathrooms: 2,
    garage: 1,
    area: 96,
    pets: false,
    furnished: true,
    security: true,
    pool: true,
    patio: false,
    grill: true,
    elevator: true,
    shortDescription: "Departamento equipado con piscina, churrasquera y parqueo.",
    longDescription: "Living comedor integrado, cocina equipada, dos dormitorios, dos baños, balcon y parqueo. El edificio ofrece piscina, salon social, churrasquera y seguridad permanente.",
    requirements: ["1 mes adelantado", "1 mes de garantia", "Expensas no incluidas", "Sin comision inmobiliaria"],
    idealFor: ["Parejas", "Home office", "Casas premium"],
    tags: ["Amoblado", "Piscina", "Balcon", "Parqueo"],
    coordinates: { lat: -17.7612, lng: -63.2014 },
    neighborhoodHighlights: ["Ventura Mall", "Restaurantes", "Oficinas"],
    images: rotatePhotos(apartmentPhotos, 4),
    ownerIndex: 2,
  }),
  makeDemo({
    id: "demo-direct-008",
    slug: "demo-monoambiente-mutualista",
    title: "Monoambiente economico cerca de Mutualista",
    type: "Departamento",
    price: 1900,
    zone: "Mutualista",
    address: "Zona Mutualista, cerca del 4to anillo",
    bedrooms: 1,
    bathrooms: 1,
    garage: 0,
    area: 30,
    pets: true,
    furnished: false,
    security: false,
    pool: false,
    patio: false,
    grill: false,
    elevator: false,
    shortDescription: "Monoambiente independiente de bajo costo, acepta mascota pequeña.",
    longDescription: "Ambiente unico con sector de cocina, baño privado y espacio para lavadora. Acceso independiente y buena conexion con transporte publico y comercio.",
    requirements: ["1 mes adelantado", "1 mes de garantia", "Sin comision inmobiliaria", "Mascota pequeña permitida"],
    idealFor: ["Persona sola", "Mascotas", "Economicos"],
    tags: ["Monoambiente", "Mascotas", "Acceso independiente", "Bajo costo"],
    coordinates: { lat: -17.7568, lng: -63.1598 },
    neighborhoodHighlights: ["Mercado Mutualista", "Transporte", "Comercio"],
    images: rotatePhotos(apartmentPhotos, 5),
    ownerIndex: 3,
  }),
  makeDemo({
    id: "demo-direct-009",
    slug: "demo-casa-condominio-las-palmas",
    title: "Casa en condominio privado en Las Palmas",
    type: "Casa",
    price: 7200,
    zone: "Las Palmas",
    address: "Las Palmas, condominio residencial",
    bedrooms: 3,
    bathrooms: 3,
    garage: 2,
    area: 220,
    pets: true,
    furnished: false,
    security: true,
    pool: true,
    patio: true,
    grill: true,
    elevator: false,
    shortDescription: "Casa segura con jardin privado y areas comunes familiares.",
    longDescription: "Tres dormitorios, principal en suite, sala familiar, living comedor, cocina con isla, lavanderia, jardin y galeria. El condominio cuenta con piscina y seguridad 24 horas.",
    requirements: ["1 mes adelantado", "2 meses de garantia", "Expensas no incluidas", "Sin comision inmobiliaria"],
    idealFor: ["Familias", "Mascotas", "Zonas tranquilas"],
    tags: ["Condominio", "Piscina", "Jardin", "Seguridad 24/7"],
    coordinates: { lat: -17.7854, lng: -63.2136 },
    neighborhoodHighlights: ["Las Palmas", "Colegios", "Areas verdes"],
    images: rotatePhotos(housePhotos, 2),
    ownerIndex: 4,
  }),
  makeDemo({
    id: "demo-direct-010",
    slug: "demo-departamento-dos-dormitorios-urbari-sur",
    title: "Departamento renovado en Urbari Sur",
    type: "Departamento",
    price: 3000,
    zone: "Urbari",
    address: "Urbari Sur, acceso rapido al 2do anillo",
    bedrooms: 2,
    bathrooms: 1,
    garage: 1,
    area: 75,
    pets: true,
    furnished: false,
    security: false,
    pool: false,
    patio: false,
    grill: false,
    elevator: false,
    shortDescription: "Departamento renovado con parqueo y servicios independientes.",
    longDescription: "Cuenta con dos dormitorios con roperos, sala comedor, cocina con cajoneria, baño completo, lavanderia y parqueo. Los servicios se pagan segun consumo.",
    requirements: ["1 mes adelantado", "1 mes de garantia", "Sin comision inmobiliaria", "Servicios segun consumo"],
    idealFor: ["Parejas", "Familias", "Mascotas"],
    tags: ["Renovado", "Parqueo", "Roperos", "Servicios independientes"],
    coordinates: { lat: -17.8031, lng: -63.1922 },
    neighborhoodHighlights: ["Urbari", "2do anillo", "Servicios"],
    images: rotatePhotos(apartmentPhotos, 6),
    ownerIndex: 5,
  }),
];

export function getDirectRentalDemoBySlug(slug: string) {
  return directRentalDemoProperties.find((property) => property.slug === slug);
}

type DemoInput = Omit<
  Property,
  | "operation"
  | "currency"
  | "city"
  | "mapUrl"
  | "whatsapp"
  | "listingPlan"
  | "publisher"
  | "agent"
  | "featured"
  | "published"
  | "availabilityConfirmedAt"
  | "isSeeded"
> & { ownerIndex: number };

function makeDemo(input: DemoInput): Property {
  return {
    ...input,
    operation: "Alquiler",
    currency: "BOB",
    city: "Santa Cruz",
    mapUrl: `https://www.google.com/maps/search/?api=1&query=${input.coordinates.lat},${input.coordinates.lng}`,
    whatsapp: "59178504969",
    listingPlan: "standard",
    publisher: demoPublisher,
    agent: makeDemoOwner(input.ownerIndex, input.zone),
    featured: false,
    published: true,
    availabilityConfirmedAt,
    isSeeded: true,
  };
}

function makeDemoOwner(index: number, zone: string): PropertyAgent {
  return {
    name: `Propietario demo ${String(index).padStart(2, "0")}`,
    role: "Propietario directo de prueba",
    email: "purplemangoadrian@gmail.com",
    phone: "+591 7850 4969",
    whatsapp: "59178504969",
    photo: "",
    areas: [zone],
    verified: false,
    responseTime: "Contacto de prueba administrado por Zentro Urbano.",
  };
}

function rotatePhotos(photos: string[], offset: number) {
  return Array.from({ length: 5 }, (_, index) => photos[(index + offset) % photos.length]);
}
