import { supportHoursLabel } from "@/lib/property-reports";

export const rentalFaq = [
  { question: "¿Qué viviendas puedo encontrar?", answer: "Casas, departamentos y monoambientes en alquiler directo con su propietario. No publicamos ventas, anticréticos ni anuncios de inmobiliarias en este catálogo." },
  { question: "¿Necesito una cuenta para buscar?", answer: "No. Puedes explorar viviendas, ver sus fotos y contactar al propietario sin registrarte. Para enviar tu propia vivienda a revisión, sí necesitas una cuenta." },
  { question: "¿Cómo publico mi alquiler?", answer: "Primero crea una cuenta con tu correo o inicia sesión, también puedes usar Google. Después añade fotos, información de la vivienda, precio y condiciones. Al confirmar, recibimos una solicitud vinculada a tu cuenta." },
  { question: "¿Mi vivienda se publica al terminar los pasos?", answer: "No de inmediato. Una persona del equipo revisa las fotos, el precio y los datos antes de publicarla, y puede pedirte aclaraciones. Por ahora no verificamos la identidad del propietario. Puedes ver el estado de tu solicitud en Mi cuenta. El envío no garantiza su aprobación ni un plazo de publicación." },
  { question: "¿Cobran comisión? ¿Cómo gana dinero Zentro Urbano?", answer: "No cobramos comisión ni porcentaje a nadie: ni al inquilino ni al dueño. Publicar es gratis. Ganamos con servicios opcionales para dueños: paquetes mensuales con fotos profesionales, ayuda con el contrato y una persona que muestra la vivienda una vez al mes, y anuncios destacados, que siempre llevan la etiqueta «Destacada · servicio pagado». El alquiler y la garantía se acuerdan directamente con el propietario." },
  { question: "¿Qué pasa si no conozco un dato?", answer: "No lo inventes. Puedes dejar sin informar los baños o la superficie. Confirma directamente con el propietario cualquier característica, gasto o condición pendiente antes de acordar una visita o un pago." },
  { question: "¿Cómo funciona la revisión de fotos?", answer: "El formulario revisa formato, tamaño, resolución, luminosidad y señales de desenfoque mediante reglas programadas. Tú indicas qué ambiente muestra cada foto. Esa revisión no acredita la identidad del propietario ni la autenticidad de una vivienda." },
  { question: "¿Se conserva lo que estaba completando?", answer: "Sí. Los campos del formulario, las fotos y el ambiente que elegiste para cada una se guardan como borrador para tu cuenta en este navegador. Si recargas o cierras la página, siguen ahí al volver. Antes de guardarlas achicamos las fotos para que se envíen más rápido. En una ventana privada o si el navegador no permite guardar datos, las fotos deben volver a adjuntarse. Puedes borrar el borrador desde el formulario." },
  { question: "¿Cómo llego a una vivienda?", answer: "Abre su ficha y pulsa Cómo llegar en el mapa. Se abrirá Google Maps para calcular la ruta. Si el mapa muestra un círculo, la ubicación es aproximada: confirma la dirección exacta con el propietario antes de ir. Cuando el dueño confirmó el punto, la ficha lo dice." },
  { question: "¿Cómo reporto un anuncio o una vivienda no disponible?", answer: `En la ficha, toca «Reportar este anuncio» y elige el motivo. No necesitas cuenta. Revisamos los reportes ${supportHoursLabel} y podemos corregir o retirar la publicación. Si te pidieron dinero antes de la visita, escríbenos también por WhatsApp. No envíes contraseñas, códigos de acceso ni datos bancarios por el chat de ayuda.` },
  { question: "¿Cuesta publicar mi vivienda?", answer: "No. Publicar es gratis. Si quieres ayuda, ofrecemos paquetes mensuales opcionales: fotos profesionales, ayuda con el contrato y una persona que muestra tu vivienda 1 vez al mes. Consúltanos por WhatsApp." },
  { question: "¿Qué hago cuando ya alquilé mi vivienda?", answer: "En Mi cuenta toca «Ya se alquiló». El anuncio deja de mostrarse y no se borra nada. Si vuelve a quedar libre, toca «Volver a publicar»: lo revisamos antes de mostrarlo de nuevo." },
  { question: "¿Por qué me piden confirmar que sigue disponible?", answer: "Tu anuncio se ve «Disponible» durante 21 días desde tu última confirmación, o hasta que 5 personas avisen que ya no está. Después dice «Disponibilidad por confirmar». Confírmalo en Mi cuenta con «Sigue disponible»." },
  { question: "¿Qué significa \"Disponible\" en un anuncio?", answer: "Que el dueño o nuestro equipo confirmó en los últimos 21 días que la vivienda sigue libre. Pasados 21 días, o si cinco personas avisan que ya no está disponible, el anuncio pasa a \"Disponibilidad por confirmar\" hasta que el dueño lo confirme otra vez." },
  { question: "¿Qué significa \"personas vieron este anuncio\"?", answer: "Es la cantidad de personas que abrieron la ficha. Contamos cada teléfono o computadora una sola vez, aunque la abra varias veces, y no contamos buscadores ni programas automáticos. El número es público para que sepas cuánto interés tiene una vivienda." },
  { question: "¿Verifican la identidad de los dueños?", answer: "Por ahora no. Revisamos cada anuncio antes de publicarlo, pero eso no acredita quién es el propietario. Antes de pagar, pide ver el Folio Real o una factura de luz o agua a su nombre y no pagues nada antes de visitar la vivienda." },
];
