import { supportHoursLabel } from "@/lib/property-reports";

export const rentalFaq = [
  { question: "¿Qué viviendas puedo encontrar?", answer: "Casas, departamentos y monoambientes en alquiler directo con su propietario. No publicamos ventas, anticréticos ni anuncios de inmobiliarias en este catálogo." },
  { question: "¿Necesito una cuenta para buscar?", answer: "No. Puedes explorar viviendas, ver sus fotos y contactar al propietario sin registrarte. Para enviar tu propia vivienda a revisión, sí necesitas una cuenta." },
  { question: "¿Cómo publico mi alquiler?", answer: "Primero crea una cuenta con tu correo o inicia sesión, también puedes usar Google. Después añade fotos, información de la vivienda, precio y condiciones. Al confirmar, recibimos una solicitud vinculada a tu cuenta." },
  { question: "¿Mi vivienda se publica al terminar los pasos?", answer: "No de inmediato. Una persona del equipo revisa las fotos, el precio y los datos antes de publicarla, y puede pedirte aclaraciones. Por ahora no verificamos la identidad del propietario. Puedes ver el estado de tu solicitud en Mi cuenta. El envío no garantiza su aprobación ni un plazo de publicación." },
  { question: "¿Cobran comisión de intermediación?", answer: "Zentro Urbano no intermedia el contrato ni cobra una comisión de intermediación al inquilino. El alquiler y la garantía se acuerdan directamente con el propietario. La publicidad de servicios para el hogar se ofrece por separado." },
  { question: "¿Qué pasa si no conozco un dato?", answer: "No lo inventes. Puedes dejar sin informar los baños o la superficie. Confirma directamente con el propietario cualquier característica, gasto o condición pendiente antes de acordar una visita o un pago." },
  { question: "¿Cómo funciona la revisión de fotos?", answer: "El formulario revisa formato, tamaño, resolución, luminosidad y señales de desenfoque mediante reglas programadas. Tú indicas qué ambiente muestra cada foto. Esa revisión no acredita la identidad del propietario ni la autenticidad de una vivienda." },
  { question: "¿Se conserva lo que estaba completando?", answer: "Los campos del formulario se guardan como borrador para tu cuenta en este navegador, cuando el almacenamiento está disponible. Por seguridad y para no ocupar espacio innecesario, las fotos deben volver a adjuntarse si recargas o cierras la página." },
  { question: "¿Cómo llego a una vivienda?", answer: "Abre su ficha y pulsa Cómo llegar en el mapa. Se abrirá Google Maps para calcular la ruta. Algunos marcadores son aproximados: confirma la dirección y coordina la visita con el propietario." },
  { question: "¿Cómo reporto un anuncio o una vivienda no disponible?", answer: `Usa «Reportar este anuncio» en la ficha o escríbenos por WhatsApp o correo con el enlace y el motivo. Atendemos ${supportHoursLabel}. Podemos revisar la publicación y corregirla u ocultarla. No envíes contraseñas, códigos de acceso ni datos bancarios por el chat de ayuda.` },
  { question: "¿Cuesta publicar mi vivienda?", answer: "No. Publicar es gratis. Si quieres ayuda, ofrecemos paquetes mensuales opcionales: fotos profesionales, ayuda con el contrato y una persona que muestra tu vivienda 1 vez al mes. Consúltanos por WhatsApp." },
  { question: "¿Qué hago cuando ya alquilé mi vivienda?", answer: "En Mi cuenta toca «Ya se alquiló». El anuncio deja de mostrarse y no se borra nada. Si vuelve a quedar libre, toca «Volver a publicar»: lo revisamos antes de mostrarlo de nuevo." },
  { question: "¿Por qué me piden confirmar que sigue disponible?", answer: "Tu anuncio se ve «Disponible» durante 21 días desde tu última confirmación, o hasta que 5 personas avisen que ya no está. Después dice «Disponibilidad por confirmar». Confírmalo en Mi cuenta con «Sigue disponible»." },
];
