export const rentalFaq = [
  { question: "¿Qué viviendas puedo encontrar?", answer: "Casas, departamentos y monoambientes en alquiler directo con su propietario. No publicamos ventas, anticréticos ni anuncios de inmobiliarias en este catálogo." },
  { question: "¿Necesito una cuenta para buscar?", answer: "No. Puedes explorar viviendas, ver sus fotos y contactar al propietario sin registrarte. Para enviar tu propia vivienda a revisión, sí necesitas una cuenta." },
  { question: "¿Cómo publico mi alquiler?", answer: "Primero crea una cuenta con tu correo o inicia sesión, también puedes usar Google. Después añade fotos, información de la vivienda, precio y condiciones. Al confirmar, recibimos una solicitud vinculada a tu cuenta." },
  { question: "¿Mi vivienda se publica al terminar los pasos?", answer: "No de inmediato. El envío queda pendiente de revisión manual. Revisamos la información y podemos pedirte aclaraciones antes de publicarla. El envío no garantiza su aprobación ni un plazo de publicación." },
  { question: "¿Cobran comisión de intermediación?", answer: "Zentro Urbano no intermedia el contrato ni cobra una comisión de intermediación al inquilino. El alquiler y la garantía se acuerdan directamente con el propietario. La publicidad de servicios para el hogar se ofrece por separado." },
  { question: "¿Qué pasa si no conozco un dato?", answer: "No lo inventes. Puedes dejar sin informar los baños o la superficie. Confirma directamente con el propietario cualquier característica, gasto o condición pendiente antes de acordar una visita o un pago." },
  { question: "¿Cómo funciona la revisión de fotos?", answer: "El formulario revisa formato, tamaño, resolución, luminosidad y señales de desenfoque mediante reglas programadas. Tú indicas qué ambiente muestra cada foto. Esa revisión no acredita la identidad del propietario ni la autenticidad de una vivienda." },
  { question: "¿Se conserva lo que estaba completando?", answer: "Los campos del formulario se guardan como borrador para tu cuenta en este navegador, cuando el almacenamiento está disponible. Por seguridad y para no ocupar espacio innecesario, las fotos deben volver a adjuntarse si recargas o cierras la página." },
  { question: "¿Cómo llego a una vivienda?", answer: "Abre su ficha y pulsa Cómo llegar en el mapa. Se abrirá Google Maps para calcular la ruta. Algunos marcadores son aproximados: confirma la dirección y coordina la visita con el propietario." },
  { question: "¿Cómo reporto un anuncio o una vivienda no disponible?", answer: "Escríbenos por WhatsApp o correo con el enlace de la ficha y el motivo. Podemos revisar la publicación y corregirla o retirarla. No envíes contraseñas, códigos de acceso ni datos bancarios por el chat de ayuda." },
];
